### ISSUE TITLE
The website shows the content for STI

### ISSUE THREAD

**Issue by mehulved** [mumbaipollution/mumbaipollution.org#2]
The current code has been clone from savetheinternet.in website and thus shows the content for it. The content needs to be modified to display the content for mumbaipollution.in

**Comment by mehulved** [comment]
This is a superset of #1 which only deals with index page. We'll also need to update the graphics, contents of the letter, etc.

**Comment by indcoder** [comment]
Visible STI content has been replaced with Mumbai pollution artifacts : logo, favicon..ico and textual content
